// Dynamic sitemap generation.
//
// Pure function: takes the route registry + a list of editorial entries,
// returns a single XML string. The build script (scripts/distribution/
// build-distribution.mjs) calls this once at `closeBundle` time and writes
// the result to `dist/sitemap.xml`.
//
// Replaces the hand-maintained public/sitemap.xml with a derived artifact
// that scales: every new editorial entry, every new collection, every new
// hub becomes one row in the sitemap by definition.

import { SITE } from "../constants";
import { getStaticSurfaces, UPDATE_FREQ } from "./routes";
import { EDITORIAL_COLLECTIONS } from "../editorial/collections-config";

const XML_HEADER = '<?xml version="1.0" encoding="UTF-8"?>';

/**
 * Build an entry-level sitemap row from a content-collection entry.
 * Editorial entries are weighted slightly above system pages but below hubs;
 * lastmod prefers `updatedAt`, falls back to `date`.
 */
function entryRow(entry, config, baseUrl) {
    const path = entry.href || `/content/${config.slug}/${entry.slug}`;
    const loc = `${baseUrl}${path}`;
    const lastmod = entry.updatedAt || entry.date || null;
    return {
        loc,
        lastmod,
        changefreq: UPDATE_FREQ.MONTHLY,
        priority: 0.7,
    };
}

function surfaceRow(surface, baseUrl) {
    return {
        loc: `${baseUrl}${surface.path}`,
        lastmod: null,
        changefreq: surface.changefreq,
        priority: surface.priority,
    };
}

function escXml(value) {
    if (value === null || value === undefined) return "";
    return String(value)
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;");
}

function renderRow({ loc, lastmod, changefreq, priority }) {
    const lines = [
        "  <url>",
        `    <loc>${escXml(loc)}</loc>`,
    ];
    if (lastmod) lines.push(`    <lastmod>${escXml(lastmod)}</lastmod>`);
    if (changefreq) lines.push(`    <changefreq>${escXml(changefreq)}</changefreq>`);
    if (priority !== undefined && priority !== null) {
        lines.push(`    <priority>${Number(priority).toFixed(2)}</priority>`);
    }
    lines.push("  </url>");
    return lines.join("\n");
}

/**
 * buildSitemap({ entries }) — entries is the result of getAllEntries().
 *
 * Returns the full XML document as a string, ready to write to disk.
 * Order: hubs → collections → entries → system pages. Inside each band, by
 * priority desc.
 */
export function buildSitemap({ entries = [] } = {}) {
    const baseUrl = SITE.url.replace(/\/$/, "");
    const surfaces = getStaticSurfaces();

    const collectionRows = [];
    const entryRows = [];

    // Map entry types back to collection configs once
    const byType = new Map(EDITORIAL_COLLECTIONS.map((c) => [c.type, c]));

    for (const entry of entries) {
        const config = byType.get(entry.type);
        if (!config) continue;
        entryRows.push(entryRow(entry, config, baseUrl));
    }

    for (const surface of surfaces) {
        collectionRows.push(surfaceRow(surface, baseUrl));
    }

    // Stable ordering:
    //   1. canonical surfaces by priority desc, then collections by slug
    //   2. entries by lastmod desc
    collectionRows.sort((a, b) => (b.priority || 0) - (a.priority || 0));
    entryRows.sort((a, b) => {
        const ad = a.lastmod || "";
        const bd = b.lastmod || "";
        if (ad < bd) return 1;
        if (ad > bd) return -1;
        return a.loc.localeCompare(b.loc);
    });

    const allRows = [...collectionRows, ...entryRows];

    return [
        XML_HEADER,
        `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">`,
        ...allRows.map(renderRow),
        `</urlset>`,
        "",
    ].join("\n");
}

/**
 * Build a feed-discovery index file (RFC for plain-text "feeds.txt"-style
 * registries does not exist, but we ship one as documentation).
 */
export function buildFeedIndex({ feedSlugs = [] } = {}) {
    const baseUrl = SITE.url.replace(/\/$/, "");
    const lines = [
        `# ${SITE.name} — Distribution feeds`,
        `# Generated by the YuvalCode distribution pipeline.`,
        ``,
    ];
    for (const slug of feedSlugs) {
        lines.push(`${slug}: ${baseUrl}/feeds/${slug}.xml (RSS)`);
        lines.push(`${slug}: ${baseUrl}/feeds/${slug}.atom.xml (Atom)`);
        lines.push(`${slug}: ${baseUrl}/feeds/${slug}.json (JSON Feed)`);
    }
    lines.push("");
    return lines.join("\n");
}
