// Post-build distribution generator.
//
// Runs after `vite build` (chained via package.json scripts) and emits:
//   dist/sitemap.xml
//   dist/feeds/<slug>.xml         (RSS 2.0)
//   dist/feeds/<slug>.atom.xml    (Atom 1.0)
//   dist/feeds/<slug>.json        (JSON Feed 1.1)
//   dist/feeds/index.txt
//   dist/feeds/README.md
//
// Uses Vite's standalone SSR loader to hydrate the JSX editorial modules.
// Keeps the main build pipeline untouched — running this in a Vite plugin's
// `closeBundle` collides with the parent build's transform context, so the
// generator lives in a sibling step instead.
//
// No new dependencies. Vite + @vitejs/plugin-react are already project deps.

import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = resolve(__dirname, "../..");
const DIST_DIR = resolve(PROJECT_ROOT, "dist");

const log = (...args) => console.log("\x1b[36m[distribution]\x1b[0m", ...args);

async function main() {
    const { createServer } = await import("vite");
    const react = (await import("@vitejs/plugin-react")).default;

    const server = await createServer({
        configFile: false,
        root: PROJECT_ROOT,
        server: { middlewareMode: true, hmr: false, watch: null },
        appType: "custom",
        logLevel: "silent",
        clearScreen: false,
        plugins: [react()],
    });

    try {
        const distribution = await server.ssrLoadModule(
            "/src/lib/distribution/index.js",
        );
        const content = await server.ssrLoadModule("/src/lib/content/index.js");

        const allEntries = content.getAllEntries();
        log(`Hydrated ${allEntries.length} editorial entries.`);

        // 1. Sitemap.
        const sitemapXml = distribution.buildSitemap({ entries: allEntries });
        await writeOutput(join(DIST_DIR, "sitemap.xml"), sitemapXml);
        log(`sitemap.xml — ${prettyBytes(sitemapXml.length)}.`);

        // 2. Feeds — global + per editorial collection × 3 serializations.
        const feedSlugs = distribution.getFeedSlugs();
        let totalFeedBytes = 0;
        for (const slug of feedSlugs) {
            let entries;
            if (slug === "all") {
                entries = allEntries;
            } else {
                const config = distribution.getCollectionForFeedSlug(slug);
                if (!config) continue;
                entries = allEntries.filter((e) => e.type === config.type);
            }
            entries = entries.slice().sort(byDateDesc);
            const model = distribution.buildFeedModel({ slug, entries });

            const rss = distribution.renderRss(model);
            const atom = distribution.renderAtom(model);
            const json = distribution.renderJsonFeed(model);

            await writeOutput(join(DIST_DIR, "feeds", `${slug}.xml`), rss);
            await writeOutput(join(DIST_DIR, "feeds", `${slug}.atom.xml`), atom);
            await writeOutput(join(DIST_DIR, "feeds", `${slug}.json`), json);

            totalFeedBytes += rss.length + atom.length + json.length;
        }
        log(
            `feeds × ${feedSlugs.length} (RSS + Atom + JSON Feed) — ${prettyBytes(totalFeedBytes)}.`,
        );

        // 3. Feed catalog.
        const catalog = distribution.buildFeedIndex({ feedSlugs });
        await writeOutput(join(DIST_DIR, "feeds", "index.txt"), catalog);

        // 4. Readme — useful when diffing dist artifacts.
        const readme = [
            `# Distribution outputs`,
            ``,
            `Auto-generated by scripts/distribution/post-build.mjs.`,
            `Do not edit by hand.`,
            ``,
            `## Feeds`,
            ...feedSlugs.flatMap((slug) => [
                ``,
                `### ${slug}`,
                `- /feeds/${slug}.xml`,
                `- /feeds/${slug}.atom.xml`,
                `- /feeds/${slug}.json`,
            ]),
            ``,
        ].join("\n");
        await writeOutput(join(DIST_DIR, "feeds", "README.md"), readme);

        log(`distribution snapshot ready in ${DIST_DIR}.`);
    } finally {
        await server.close();
    }
}

async function writeOutput(path, content) {
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, content, "utf8");
}

function byDateDesc(a, b) {
    if (!a.date && !b.date) return 0;
    if (!a.date) return 1;
    if (!b.date) return -1;
    return b.date.localeCompare(a.date);
}

function prettyBytes(n) {
    if (n < 1024) return `${n}B`;
    return `${(n / 1024).toFixed(2)}kB`;
}

main().catch((err) => {
    console.error("[distribution] generation failed:", err);
    process.exitCode = 1;
});
