// Static surface index — every shipped top-level route + its synonyms.
//
// Keeps the search modal usable as a keyboard-driven nav (Cmd+K → "ai" → /ai)
// even before any content is authored. Hebrew + English aliases are first-class
// because the brand is bilingual.

export const ROUTE_ENTRIES = Object.freeze([
    {
        id: "route:home",
        kind: "route",
        title: "בית",
        subtitle: "Home · ראשי",
        href: "/",
        keywords: ["home", "בית", "ראשי", "yuvalcode"],
        eyebrow: "Surface",
    },
    {
        id: "route:content",
        kind: "route",
        title: "Content · האקוסיסטם",
        subtitle: "Content · 8 pillars",
        href: "/content",
        keywords: ["content", "תוכן", "pillars", "ecosystem", "אקוסיסטם"],
        eyebrow: "Surface",
    },
    {
        id: "route:ai",
        kind: "route",
        title: "AI · בנייה עם AI בפומבי",
        subtitle: "AI Track",
        href: "/ai",
        keywords: ["ai", "claude", "anti gravity", "agents", "סוכנים", "בינה מלאכותית"],
        eyebrow: "Surface",
    },
    {
        id: "route:projects",
        kind: "route",
        title: "Projects · מערכות אמיתיות",
        subtitle: "Projects · Built in public",
        href: "/projects",
        keywords: ["projects", "פרויקטים", "case study", "systems", "מערכות"],
        eyebrow: "Surface",
    },
    {
        id: "route:stack",
        kind: "route",
        title: "Stack · Creator OS",
        subtitle: "Creator Stack",
        href: "/stack",
        keywords: ["stack", "tools", "obsidian", "claude code", "vs code", "vault", "מחסנית", "כלים"],
        eyebrow: "Surface",
    },
    {
        id: "route:exams",
        kind: "route",
        title: "קטלוג מה״ט",
        subtitle: "Exams · C# · Mahat",
        href: "/exams",
        keywords: ["exams", "מה״ט", "מהט", "c#", "csharp", "מבחן"],
        eyebrow: "Surface",
    },
    {
        id: "route:videos",
        kind: "route",
        title: "סרטונים",
        subtitle: "Videos catalog",
        href: "/videos",
        keywords: ["videos", "סרטונים", "פלייליסטים"],
        eyebrow: "Surface",
    },
    {
        id: "route:work-with-me",
        kind: "route",
        title: "Work With Me",
        subtitle: "Collaboration · Consulting",
        href: "/work-with-me",
        keywords: ["work", "collab", "consulting", "hire", "להעסיק", "שיתוף פעולה"],
        eyebrow: "Surface",
    },
    {
        id: "route:about",
        kind: "route",
        title: "אודות",
        subtitle: "About · Creator origin",
        href: "/about",
        keywords: ["about", "אודות", "סיפור", "yuval"],
        eyebrow: "Surface",
    },
    {
        id: "route:contact",
        kind: "route",
        title: "צור קשר",
        subtitle: "Contact",
        href: "/contact",
        keywords: ["contact", "צור קשר", "קשר", "email"],
        eyebrow: "Surface",
    },
    {
        id: "route:newsletter",
        kind: "route",
        title: "הצטרף לניוזלטר",
        subtitle: "Newsletter signup",
        href: "/contact?subject=newsletter",
        keywords: ["newsletter", "ניוזלטר", "subscribe", "email"],
        eyebrow: "Action",
    },
]);
